import type { TtsVoiceOption, TtsProvider } from '@/types';

export const KNOWN_TTS_PROVIDERS = [
  {
    id: 'gemini',
    name: 'Google Gemini TTS',
    description: 'Native Google multi-modal neural speech with natural breathing, pedagogical pacing, and warm vocal resonance.',
    defaultModel: 'gemini-3.1-flash-tts-preview',
    defaultVoice: 'Kore',
    endpoint: 'https://generativelanguage.googleapis.com',
    placeholder: 'AIzaSy...',
    apiKeyUrl: 'https://aistudio.google.com/apikey',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter Audio',
    description: 'Unified gateway for OpenRouter speech models (Kokoro 82M, Gemini Flash TTS, Deepgram Flux Free, etc.).',
    defaultModel: 'hexgrad/kokoro-82m',
    defaultVoice: 'af_heart',
    endpoint: 'https://openrouter.ai/api/v1/audio/speech',
    placeholder: 'sk-or-v1-...',
    apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai',
    name: 'OpenAI Audio (TTS)',
    description: 'High-clarity studio-grade voices powered by OpenAI TTS-1 and TTS-1 HD.',
    defaultModel: 'tts-1',
    defaultVoice: 'alloy',
    endpoint: 'https://api.openai.com/v1/audio/speech',
    placeholder: 'sk-proj-...',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Hyper-realistic multilingual voice synthesis with emotional depth and human-like intonation.',
    defaultModel: 'eleven_multilingual_v2',
    defaultVoice: '21m00Tcm4TlvDq8ikWAM', // Rachel
    endpoint: 'https://api.elevenlabs.io/v1/text-to-speech',
    placeholder: 'xi-...',
    apiKeyUrl: 'https://elevenlabs.io',
  },
  {
    id: 'groq',
    name: 'Groq Cloud / Kokoro',
    description: 'Low-latency LPU speech synthesis or fast OpenAI-compatible audio endpoint.',
    defaultModel: 'kokoro',
    defaultVoice: 'af_heart',
    endpoint: 'https://api.groq.com/openai/v1/audio/speech',
    placeholder: 'gsk_...',
    apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-Compatible TTS',
    description: 'Self-hosted Kokoro-FastAPI, AllTalk, LM Studio, or private TTS server.',
    defaultModel: 'tts-1',
    defaultVoice: 'default',
    endpoint: 'http://localhost:8000/v1/audio/speech',
    placeholder: 'Optional API Key',
  },
  {
    id: 'browser',
    name: 'Web Speech Engine (Browser Fallback)',
    description: 'Instant client-side speech synthesis utilizing your operating system voices. 100% free and works offline.',
    defaultModel: 'browser-native',
    defaultVoice: 'default',
    endpoint: '',
    placeholder: 'No API Key Required',
  },
];

export const TTS_VOICES: Record<TtsProvider, TtsVoiceOption[]> = {
  gemini: [
    {
      id: 'Kore',
      name: 'Kore',
      gender: 'female',
      accent: 'Warm & Pedagogical',
      description: 'Soothing, warm teacher cadence. Ideal for conceptual explanations & student lectures.',
      provider: 'gemini',
    },
    {
      id: 'Zephyr',
      name: 'Zephyr',
      gender: 'neutral',
      accent: 'Calm & Intellectual',
      description: 'Gentle, balanced, and articulate. Perfect for first-principles derivations.',
      provider: 'gemini',
    },
    {
      id: 'Puck',
      name: 'Puck',
      gender: 'male',
      accent: 'Engaging & Dynamic',
      description: 'Energetic, crisp, and expressive. Great for viva questions and slide lectures.',
      provider: 'gemini',
    },
    {
      id: 'Charon',
      name: 'Charon',
      gender: 'male',
      accent: 'Deep & Authoritative',
      description: 'Senior clinical attending resonance. Excellent for diagnostic case briefings.',
      provider: 'gemini',
    },
    {
      id: 'Fenrir',
      name: 'Fenrir',
      gender: 'male',
      accent: 'Direct & Clear',
      description: 'Fast-paced, confident medical grand rounds presentation timbre.',
      provider: 'gemini',
    },
  ],
  openai: [
    { id: 'alloy', name: 'Alloy', gender: 'neutral', accent: 'Balanced & Direct', description: 'Versatile and articulate general speaker.', provider: 'openai' },
    { id: 'echo', name: 'Echo', gender: 'male', accent: 'Warm & Resonant', description: 'Smooth, deep narrator voice.', provider: 'openai' },
    { id: 'fable', name: 'Fable', gender: 'neutral', accent: 'British Nuance', description: 'Expressive accent for detailed academic study.', provider: 'openai' },
    { id: 'onyx', name: 'Onyx', gender: 'male', accent: 'Authoritative & Deep', description: 'Strong clinical debrief tone.', provider: 'openai' },
    { id: 'nova', name: 'Nova', gender: 'female', accent: 'Energetic & Crisp', description: 'Engaging and lively teacher persona.', provider: 'openai' },
    { id: 'shimmer', name: 'Shimmer', gender: 'female', accent: 'Clear & Soothing', description: 'Soft, pleasant cadence for relaxed study.', provider: 'openai' },
  ],
  openrouter: [
    { id: 'af_heart', name: 'Heart (Kokoro)', gender: 'female', accent: 'Warm & Natural', description: 'Top neural voice on OpenRouter Kokoro. Soothing & articulate.', provider: 'openrouter' },
    { id: 'am_adam', name: 'Adam (Kokoro)', gender: 'male', accent: 'Clear Academic', description: 'Crisp, confident male lecture delivery.', provider: 'openrouter' },
    { id: 'af_bella', name: 'Bella (Kokoro)', gender: 'female', accent: 'Expressive & Engaging', description: 'Dynamic cadence for lively explanations.', provider: 'openrouter' },
    { id: 'am_michael', name: 'Michael (Kokoro)', gender: 'male', accent: 'Deep & Authoritative', description: 'Deep, steady academic resonance.', provider: 'openrouter' },
    { id: 'Kore', name: 'Kore (Gemini)', gender: 'female', accent: 'Pedagogical', description: 'Google neural voice via OpenRouter Gemini TTS.', provider: 'openrouter' },
    { id: 'Puck', name: 'Puck (Gemini)', gender: 'male', accent: 'Dynamic', description: 'Google energetic voice via OpenRouter Gemini TTS.', provider: 'openrouter' },
    { id: 'aura-asteria-en', name: 'Asteria (Deepgram)', gender: 'female', accent: 'Fluent US', description: 'Fast, natural Deepgram voice (works with deepgram/flux-tts:free).', provider: 'openrouter' },
    { id: 'alloy', name: 'Alloy (Auto-Mapped)', gender: 'neutral', accent: 'Balanced', description: 'Compatible alias mapped to Kokoro Heart.', provider: 'openrouter' },
    { id: 'echo', name: 'Echo (Auto-Mapped)', gender: 'male', accent: 'Resonant', description: 'Compatible alias mapped to Kokoro Adam.', provider: 'openrouter' },
  ],
  elevenlabs: [
    { id: '21m00Tcm4TlvDq8ikWAM', name: 'Rachel', gender: 'female', accent: 'Calm American', description: 'Warm, professional, soothing medical educator.', provider: 'elevenlabs' },
    { id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam', gender: 'male', accent: 'Deep American', description: 'Experienced attending physician narration.', provider: 'elevenlabs' },
    { id: 'ErXwobaYiN019PkySvjV', name: 'Antoni', gender: 'male', accent: 'Crisp & Articulate', description: 'Clear structured academic lecture voice.', provider: 'elevenlabs' },
    { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Bella', gender: 'female', accent: 'Soft & Expressive', description: 'Gentle, patient Feynman-style teacher.', provider: 'elevenlabs' },
    { id: 'AZnzlk1XvdvUeBnXmlld', name: 'Domi', gender: 'female', accent: 'Strong & Confident', description: 'Concise medical review delivery.', provider: 'elevenlabs' },
  ],
  groq: [
    { id: 'af_heart', name: 'Heart (Kokoro)', gender: 'female', accent: 'Warm Natural', description: 'Ultra-fast neural voice for rapid study.', provider: 'groq' },
    { id: 'am_adam', name: 'Adam (Kokoro)', gender: 'male', accent: 'Clear Academic', description: 'Fast concise lecture audio.', provider: 'groq' },
    { id: 'alloy', name: 'Alloy (Groq API)', gender: 'neutral', accent: 'Direct', description: 'Standard fast inference audio.', provider: 'groq' },
  ],
  custom: [
    { id: 'default', name: 'Server Default Voice', gender: 'neutral', accent: 'Custom Host', description: 'Uses whatever voice is configured on your custom endpoint.', provider: 'custom' },
  ],
  browser: [
    { id: 'default', name: 'Browser Default Voice', gender: 'neutral', accent: 'System Native', description: 'Native operating system speech synthesizer.', provider: 'browser' },
  ],
};
