import type { TtsVoiceOption, TtsProvider } from '@/types';

export const KNOWN_TTS_PROVIDERS = [
  {
    id: 'gemini',
    name: 'Google Gemini TTS',
    description: 'Native Google multi-modal neural speech with natural breathing, pedagogical pacing, and warm vocal resonance.',
    defaultModel: 'gemini-3.1-flash-tts-preview',
    defaultVoice: 'Kore',
    endpoint: 'https://generativelanguage.googleapis.com',
    placeholder: 'AIzaSy...',
    apiKeyUrl: 'https://aistudio.google.com/apikey',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter Audio',
    description: 'Unified gateway for OpenRouter speech models and multi-provider audio synthesis.',
    defaultModel: 'openai/tts-1',
    defaultVoice: 'alloy',
    endpoint: 'https://openrouter.ai/api/v1/audio/speech',
    placeholder: 'sk-or-v1-...',
    apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai',
    name: 'OpenAI Audio (TTS)',
    description: 'High-clarity studio-grade voices powered by OpenAI TTS-1 and TTS-1 HD.',
    defaultModel: 'tts-1',
    defaultVoice: 'alloy',
    endpoint: 'https://api.openai.com/v1/audio/speech',
    placeholder: 'sk-proj-...',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Hyper-realistic multilingual voice synthesis with emotional depth and human-like intonation.',
    defaultModel: 'eleven_multilingual_v2',
    defaultVoice: '21m00Tcm4TlvDq8ikWAM', // Rachel
    endpoint: 'https://api.elevenlabs.io/v1/text-to-speech',
    placeholder: 'xi-...',
    apiKeyUrl: 'https://elevenlabs.io',
  },
  {
    id: 'groq',
    name: 'Groq Cloud / Orpheus',
    description: 'Ultra-low latency LPU speech synthesis powered by CanopyLabs Orpheus.',
    defaultModel: 'canopylabs/orpheus-v1-english',
    defaultVoice: 'autumn',
    endpoint: 'https://api.groq.com/openai/v1/audio/speech',
    placeholder: 'gsk_...',
    apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'sarvam',
    name: 'Sarvam AI (Bulbul Neural TTS)',
    description: 'State-of-the-art Indian neural TTS supporting 10 Indian languages and Indian-accented English.',
    defaultModel: 'bulbul:v3',
    defaultVoice: 'shubh',
    endpoint: 'https://api.sarvam.ai/text-to-speech',
    placeholder: 'api-subscription-key from sarvam.ai',
    apiKeyUrl: 'https://sarvam.ai',
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-Compatible TTS',
    description: 'Self-hosted Kokoro-FastAPI, AllTalk, Sarvam, LM Studio, or private TTS server.',
    defaultModel: 'tts-1',
    defaultVoice: 'default',
    endpoint: 'http://localhost:8000/v1/audio/speech',
    placeholder: 'Optional API Key',
  },
  {
    id: 'browser',
    name: 'Web Speech Engine (Browser Fallback)',
    description: 'Instant client-side speech synthesis utilizing your operating system voices. 100% free and works offline.',
    defaultModel: 'browser-native',
    defaultVoice: 'default',
    endpoint: '',
    placeholder: 'No API Key Required',
  },
];

export const TTS_VOICES: Record<TtsProvider, TtsVoiceOption[]> = {
  gemini: [
    {
      id: 'Kore',
      name: 'Kore',
      gender: 'female',
      accent: 'Warm & Pedagogical',
      description: 'Soothing, warm teacher cadence. Ideal for conceptual explanations & student lectures.',
      provider: 'gemini',
    },
    {
      id: 'Zephyr',
      name: 'Zephyr',
      gender: 'neutral',
      accent: 'Calm & Intellectual',
      description: 'Gentle, balanced, and articulate. Perfect for first-principles derivations.',
      provider: 'gemini',
    },
    {
      id: 'Puck',
      name: 'Puck',
      gender: 'male',
      accent: 'Engaging & Dynamic',
      description: 'Energetic, crisp, and expressive. Great for viva questions and slide lectures.',
      provider: 'gemini',
    },
    {
      id: 'Charon',
      name: 'Charon',
      gender: 'male',
      accent: 'Deep & Authoritative',
      description: 'Senior clinical attending resonance. Excellent for diagnostic case briefings.',
      provider: 'gemini',
    },
    {
      id: 'Fenrir',
      name: 'Fenrir',
      gender: 'male',
      accent: 'Direct & Clear',
      description: 'Fast-paced, confident medical grand rounds presentation timbre.',
      provider: 'gemini',
    },
  ],
  openai: [
    { id: 'alloy', name: 'Alloy', gender: 'neutral', accent: 'Balanced & Direct', description: 'Versatile and articulate general speaker.', provider: 'openai' },
    { id: 'echo', name: 'Echo', gender: 'male', accent: 'Warm & Resonant', description: 'Smooth, deep narrator voice.', provider: 'openai' },
    { id: 'fable', name: 'Fable', gender: 'neutral', accent: 'British Nuance', description: 'Expressive accent for detailed academic study.', provider: 'openai' },
    { id: 'onyx', name: 'Onyx', gender: 'male', accent: 'Authoritative & Deep', description: 'Strong clinical debrief tone.', provider: 'openai' },
    { id: 'nova', name: 'Nova', gender: 'female', accent: 'Energetic & Crisp', description: 'Engaging and lively teacher persona.', provider: 'openai' },
    { id: 'shimmer', name: 'Shimmer', gender: 'female', accent: 'Clear & Soothing', description: 'Soft, pleasant cadence for relaxed study.', provider: 'openai' },
  ],
  openrouter: [
    { id: 'af_heart', name: 'Heart (Kokoro)', gender: 'female', accent: 'Warm & Natural', description: 'Lightweight neural voice with high clarity (af_heart).', provider: 'openrouter' },
    { id: 'am_adam', name: 'Adam (Kokoro)', gender: 'male', accent: 'Clear Academic', description: 'Confident, articulate male lecture delivery (am_adam).', provider: 'openrouter' },
    { id: 'af_bella', name: 'Bella (Kokoro)', gender: 'female', accent: 'Expressive', description: 'Dynamic cadence for engaging topic walk-throughs.', provider: 'openrouter' },
    { id: 'am_michael', name: 'Michael (Kokoro)', gender: 'male', accent: 'Deep & Steady', description: 'Steady, resonant tone for deep-dive explanations.', provider: 'openrouter' },
    { id: 'alloy', name: 'Alloy (OpenRouter)', gender: 'neutral', accent: 'Direct', description: 'Standard OpenAI-compatible speech voice via OpenRouter.', provider: 'openrouter' },
    { id: 'echo', name: 'Echo (OpenRouter)', gender: 'male', accent: 'Resonant', description: 'Deep male narrator tone.', provider: 'openrouter' },
    { id: 'nova', name: 'Nova (OpenRouter)', gender: 'female', accent: 'Warm', description: 'Friendly instructor voice.', provider: 'openrouter' },
    { id: 'shimmer', name: 'Shimmer (OpenRouter)', gender: 'female', accent: 'Calm', description: 'Clear soothing audio.', provider: 'openrouter' },
  ],
  elevenlabs: [
    { id: '21m00Tcm4TlvDq8ikWAM', name: 'Rachel', gender: 'female', accent: 'Calm American', description: 'Warm, professional, soothing medical educator.', provider: 'elevenlabs' },
    { id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam', gender: 'male', accent: 'Deep American', description: 'Experienced attending physician narration.', provider: 'elevenlabs' },
    { id: 'ErXwobaYiN019PkySvjV', name: 'Antoni', gender: 'male', accent: 'Crisp & Articulate', description: 'Clear structured academic lecture voice.', provider: 'elevenlabs' },
    { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Bella', gender: 'female', accent: 'Soft & Expressive', description: 'Gentle, patient Feynman-style teacher.', provider: 'elevenlabs' },
    { id: 'AZnzlk1XvdvUeBnXmlld', name: 'Domi', gender: 'female', accent: 'Strong & Confident', description: 'Concise medical review delivery.', provider: 'elevenlabs' },
  ],
  groq: [
    { id: 'autumn', name: 'Autumn (Orpheus)', gender: 'female', accent: 'Clear & Natural', description: 'Warm, articulate, and natural delivery. Groq Orpheus default.', provider: 'groq' },
    { id: 'diana', name: 'Diana (Orpheus)', gender: 'female', accent: 'Expressive & Engaging', description: 'Lively, expressive cadence for interactive lectures.', provider: 'groq' },
    { id: 'hannah', name: 'Hannah (Orpheus)', gender: 'female', accent: 'Conversational', description: 'Friendly, easy-to-follow explanations.', provider: 'groq' },
    { id: 'austin', name: 'Austin (Orpheus)', gender: 'male', accent: 'Confident Academic', description: 'Clear, authoritative professor persona.', provider: 'groq' },
    { id: 'daniel', name: 'Daniel (Orpheus)', gender: 'male', accent: 'Dynamic & Energetic', description: 'Fast-paced, engaging delivery for rapid review.', provider: 'groq' },
    { id: 'troy', name: 'Troy (Orpheus)', gender: 'male', accent: 'Deep & Resonant', description: 'Deep, senior clinical debrief tone.', provider: 'groq' },
  ],
  sarvam: [
    { id: 'shubh', name: 'Shubh (Bulbul v3)', gender: 'male', accent: 'Indian Natural', description: 'Natural, crystal-clear Indian English cadence. Bulbul v3 default.', provider: 'sarvam' },
    { id: 'aditya', name: 'Aditya (Bulbul v3)', gender: 'male', accent: 'Energetic Academic', description: 'Dynamic professor cadence with high clarity.', provider: 'sarvam' },
    { id: 'ritu', name: 'Ritu (Bulbul v3)', gender: 'female', accent: 'Warm & Expressive', description: 'Expressive, soothing educator voice for complex concepts.', provider: 'sarvam' },
    { id: 'priya', name: 'Priya (Bulbul v3)', gender: 'female', accent: 'Soft & Pedagogical', description: 'Gentle, patient teacher persona with clear diction.', provider: 'sarvam' },
    { id: 'neha', name: 'Neha (Bulbul v3)', gender: 'female', accent: 'Professional', description: 'Sharp, clinical precision and polished presentation.', provider: 'sarvam' },
    { id: 'rahul', name: 'Rahul (Bulbul v3)', gender: 'male', accent: 'Engaging & Friendly', description: 'Conversational tone ideal for student Q&A.', provider: 'sarvam' },
    { id: 'pooja', name: 'Pooja (Bulbul v3)', gender: 'female', accent: 'Articulate & Crisp', description: 'Clear pacing, great for dense medical notes.', provider: 'sarvam' },
    { id: 'rohan', name: 'Rohan (Bulbul v3)', gender: 'male', accent: 'Conversational', description: 'Modern, balanced male tone.', provider: 'sarvam' },
    { id: 'simran', name: 'Simran (Bulbul v3)', gender: 'female', accent: 'High Clarity', description: 'Clean pronunciation for medical terminology.', provider: 'sarvam' },
    { id: 'kavya', name: 'Kavya (Bulbul v3)', gender: 'female', accent: 'Empathetic Teacher', description: 'Warm vocal resonance for patient-friendly guidance.', provider: 'sarvam' },
    { id: 'amelia', name: 'Amelia (Bulbul v3)', gender: 'female', accent: 'International English', description: 'Global English accent with modern intonation.', provider: 'sarvam' },
    { id: 'anushka', name: 'Anushka (Bulbul v2)', gender: 'female', accent: 'Classical Academic', description: 'Established classical educator persona.', provider: 'sarvam' },
    { id: 'meera', name: 'Meera (Bulbul v1/v2)', gender: 'female', accent: 'Clear Indian', description: 'Popular Bulbul v1/v2 speaker.', provider: 'sarvam' },
    { id: 'arvind', name: 'Arvind (Bulbul v1/v2)', gender: 'male', accent: 'Senior Scholar', description: 'Authoritative male cadence for case reviews.', provider: 'sarvam' },
  ],
  custom: [
    { id: 'default', name: 'Server Default Voice', gender: 'neutral', accent: 'Custom Host', description: 'Uses whatever voice is configured on your custom endpoint.', provider: 'custom' },
  ],
  browser: [
    { id: 'default', name: 'Browser Default Voice', gender: 'neutral', accent: 'System Native', description: 'Native operating system speech synthesizer.', provider: 'browser' },
  ],
};

export const SARVAM_SUPPORTED_LANGUAGES = [
  { code: 'en-IN', name: 'English (India)', native: 'English' },
  { code: 'hi-IN', name: 'Hindi', native: 'हिन्दी' },
  { code: 'bn-IN', name: 'Bengali', native: 'বাংলা' },
  { code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml-IN', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr-IN', name: 'Marathi', native: 'मराठी' },
  { code: 'od-IN', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'pa-IN', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'ta-IN', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te-IN', name: 'Telugu', native: 'తెలుగు' },
  { code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી' },
] as const;
